### ISSUE TITLE
Suggest to support HLSL file

### ISSUE THREAD

**Issue by zuig** [waqiju/UnityShaderST3#11]
Now Unity Universal RP is a powerful Render Pipeline，More and more people switch Buildin Shader to Custom Render Pipeline. Some Shader code style has been change. Universal RP no longer support cginc file，and hlsl is for used. HLSL is very similar to CGINC files. I tried adding hlsl support myself and found it worked, but I wasn't familiar with sublime packages. I don't know whether the change is correct or not. I hope official can modify to support hlsl file.

Follow is my way to add support hlsl file:
1. add hlsl file extension in UnityShader.sublime-syntax
2. add hlsl file extension in UnityShader-CG.sublime-syntax
3. The function is_enabled in UnityShader.py add .hlsl

**Comment by waqiju** [comment]
Yeah, your suggestion is definitely right. 

Thanks for your feedback. I will accept your advice and modify the codes. And I think there is still a lot work to enchance for RP Render Pipeline.
