### ISSUE TITLE
builtin_shader.symbol Does not update when changing version

### ISSUE THREAD

**Issue by LasseWestmark** [waqiju/UnityShaderST3#2]
Hi, really great plug-in but I have one problem.

When changing unity version "GoTo Definition" still points at unity 5.5.0 even though I changed it to 5.6.1

I have the right builtin shaders folder "builtin_shaders-5.6.1f1" and I do get the popup saying "toggle unity shader version success", but the "builtin_shader.symbol" file still points at "5.5.0" and the modified time stamp doesn't change at all.

Also I have to run Sublime as administrator otherwise I get a permission error when changing version.

**Comment by waqiju** [comment]
Thanks for your feedback. And the bug has been fixed.

**Comment by LasseWestmark** [comment]
Thanks, just wanted to let you know that it works perfectly on my end now as well!
