### ISSUE TITLE
注释功能经常失效没法用

### ISSUE THREAD

**Issue by mzqb** [waqiju/UnityShaderST3#4]

**Comment by Pianya** [comment]
UnityShader 模式下无法使用注释快捷键， UnityShader-CG 可以。时好时坏。照[这个](https://stackoverflow.com/questions/17742781/keyboard-shortcut-to-comment-lines-in-sublime-text-3?rq=1)修改也没用。

**Comment by waqiju** [comment]
已经尝试修复了，目前本地测试没有复现。

多谢提出反馈，最近偏忙，回复晚了，抱歉 ^-^


> UnityShader 模式下无法使用注释快捷键， UnityShader-CG 可以。时好时坏。照[这个](https://stackoverflow.com/questions/17742781/keyboard-shortcut-to-comment-lines-in-sublime-text-3?rq=1)修改也没用。

之前查阅过，可能是这个[配置文件](https://github.com/waqiju/unity_shader_st3/blob/master/Comments.tmPreferences)的关系
