### ISSUE TITLE
Do you plan to provide VSCode version?

### ISSUE THREAD

**Issue by JasonMa0012** [waqiju/UnityShaderST3#5]

**Comment by waqiju** [comment]
Has no plan recently. BecauseI am less familiar with vscode api.

**Comment by JasonMa0012** [comment]
vscode has a better user experience and a lot of users. I have tried to learn to develop vscode hlsl extensions. They use typescript and it is easy to get started. However, I have given up temporarily because I have relatively little experience. I hope you can consider the vscode version when you have time.
